<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="localhost.localdomain" name="com.gema.testjms.SoapJMS_MaxEai_TEST" tests="1" failures="0" timestamp="14 Sep 2017 07:44:44 GMT" time="0.283" errors="1">
  <testcase name="soapJMSMaxEaiOk" time="0.283" classname="com.gema.testjms.SoapJMS_MaxEai_TEST">
    <error type="com.consol.citrus.exceptions.TestCaseFailedException" message="Test case failed">
      <![CDATA[com.consol.citrus.exceptions.TestCaseFailedException: Test case failed
	at com.consol.citrus.TestCase.executeAction(TestCase.java:236)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:145)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.Citrus.run(Citrus.java:281)
	at com.consol.citrus.testng.AbstractTestNGCitrusTest.run(AbstractTestNGCitrusTest.java:112)
	at com.consol.citrus.testng.AbstractTestNGCitrusTest.run(AbstractTestNGCitrusTest.java:69)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: javax.jms.JMSSecurityException: authentication failed
	at com.consol.citrus.jms.endpoint.JmsSyncProducer.send(JmsSyncProducer.java:147)
	at com.consol.citrus.actions.SendMessageAction.doExecute(SendMessageAction.java:118)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:229)
	... 30 more
Caused by: javax.jms.JMSSecurityException: authentication failed
	at com.tibco.tibjms.Tibjmsx.buildException(Tibjmsx.java:741)
	at com.tibco.tibjms.TibjmsConnection._create(TibjmsConnection.java:1404)
	at com.tibco.tibjms.TibjmsConnection.<init>(TibjmsConnection.java:4333)
	at com.tibco.tibjms.TibjmsxCFImpl._createImpl(TibjmsxCFImpl.java:209)
	at com.tibco.tibjms.TibjmsxCFImpl._createConnection(TibjmsxCFImpl.java:253)
	at com.tibco.tibjms.TibjmsConnectionFactory.createConnection(TibjmsConnectionFactory.java:39)
	at com.consol.citrus.jms.endpoint.JmsSyncProducer.createConnection(JmsSyncProducer.java:199)
	at com.consol.citrus.jms.endpoint.JmsSyncProducer.send(JmsSyncProducer.java:84)
	... 33 more
]]>
    </error>
  </testcase> <!-- soapJMSMaxEaiOk -->
</testsuite> <!-- com.gema.testjms.SoapJMS_MaxEai_TEST -->
